version: '3.8'

services:

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    volumes:
      - ./symfony/:/var/www/symfony
    depends_on:
      - mysql
      - php
    ports:
      - "80:80"
    restart: always
    networks:
      - symfony-rabbitmq

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php
#    environment:
#      APP_ENV: dev
#      DATABASE_URL: mysql://root:root@sql:3306/symfony_db?serverVersion=5.7
    volumes:
      - ./symfony:/var/www/symfony/
#    depends_on:
#      - nginx
#      - mysql
    networks:
      - symfony-rabbitmq

  composer:
    build:
      context: .
      dockerfile: ./composer/Dockerfile
    volumes:
      - ./symfony:/var/www/symfony
    working_dir: /var/www/symfony

  mysql:
    container_name: mysql
    image: mariadb:10.5
#    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    networks:
      - symfony-rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      # HTTP management UI
      - "5672:5672"
      # The standard AMQP protocol port
      - "15672:15672"
    restart: always
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - symfony-rabbitmq

volumes:
  app-data:
    driver: local
  rabbitmq-data:
    driver: local

networks:
  symfony-rabbitmq: