version: '3.8'

services:

  php:
    image: php:8.1-fpm
    container_name: php
    restart: unless-stopped
    working_dir: /symfony
    ports:
      - "9000:9000"
    #    environment:
    #      APP_ENV: dev
    #      DATABASE_URL: mysql://root:root@sql:3306/symfony_db?serverVersion=5.7
    volumes:
      - ./:/symfony
    depends_on:
      - mysql
    networks:
      - symfony-rabbitmq

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./:/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    ports:
      - "8080:80"
    working_dir: /symfony/symfony
    restart: always
    networks:
      - symfony-rabbitmq

  composer:
    build:
      context: .
      dockerfile: ./composer/Dockerfile
    volumes:
      - ./:/symfony
    working_dir: /symfony
    depends_on:
      - php

  mysql:
    container_name: mysql
    image: mariadb:10.5
    #    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql:rw
    restart: always
    networks:
      - symfony-rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      # HTTP management UI
      - "5672:5672"
      # The standard AMQP protocol port web GUI
      - "15672:15672"
    depends_on:
      - mysql
    restart: always
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - symfony-rabbitmq

volumes:
  app-data:
    driver: local
  rabbitmq-data:
    driver: local

networks:
  symfony-rabbitmq:
    driver: bridge
